### PR TITLE
Multiple route samples are handled correctly

### LINKED ISSUE #1: If workout consists of multiple HKWorkoutRoutes the app crashes
The export file is closed after the shortest route sample is processed. The next attempt to write to the export-file results in a `NSFileHandleOperationException`.

### PR DESCRIPTION
**Pull request by mgmart**
Fixes #1

### CODE REVIEW

File: GpxExport/WorkoutDataStore.swift [hunk 1]
```diff
@@ -67,9 +68,22 @@ class WorkoutDataStore {
                         }
                         return
                     }
-                    
-                    DispatchQueue.main.async {
-                        completion(locationResults, done, error)
+
+                    if done {
+                        allDone += 1
```
Comment (pilif) [inline GpxExport/WorkoutDataStore.swift]: as far as I understand, this is about HealthKit calling the completion handler with `done=true` and then contiuing to call it some more. I've seen this happen in the past with one specific run and I don't quite understand why it would do that.

Regardless. Are you sure that incrementing by 1 and then later compareing it to the sample count is ok?

Also, I would argue that a variable called `allDone` implies a boolean but it's actually a counter here, making this slightly confusing to a reader what about a better name?

**Review by pilif — CHANGES_REQUESTED** [review]
Can you at least rename the variable?

File: GpxExport/WorkoutDataStore.swift (hunk 1 above)
Comment (mgmart) [reply GpxExport/WorkoutDataStore.swift]: If there are more route samples, then completion is called with done=true at the end of every sample. Which leads to a closed file after the first sample has ended and a crash afterwards because there are attempts to write to the file for the other samples.

Comment (mgmart) [reply GpxExport/WorkoutDataStore.swift]: My rides and runs are divided into several samples very often. I think it has to do with pausing a workout. Although it also seem to happen on rides where I stop somewhere for several minutes without having paused the workout.

You're right about the variable name. Have to think about a better one.

I did some additional tests. The last test resulted in a wrongly combined track. Have to investigate that further. Once I found the reason I will post the solution here.

**Comment by mgmart** [comment]
Changed the name of the counter.

It could happen that the route-segments were not processed in the correct order. This is fixed now.

Heart rate is now read for the time the workout took place. This should help if the heart rate readings are not attached to the workout by HealthKit.
